# 
# Vagrantfile per i progetti client-server (per esempio, i progetti asw-820-socket e asw-830-java-rmi), che prevedono:
# - un nodo server 
# - un nodo client 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu Trusty (14.04 LTS) 64 bit VirtualBox.
    config.vm.box = "ubuntu/trusty64"
    # config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/trusty64"

    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/_shared/resources e /home/asw/_shared/scripts) 
    config.vm.synced_folder "../_shared/", "/home/asw/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "server", che prevede: 
    # - Oracle Java SDK 8 
    #
    config.vm.define "server" do |node|
        node.vm.hostname = "server"    
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true

        # node.vm.network "forwarded_port", guest: 8080, host: 8080
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        node.vm.provision :shell, :inline => "echo '10.11.1.101 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.201 client' >> /etc/hosts"
  
		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo server completata'"

    end

    #
    # Configurazione del nodo "client", che prevede: 
    # - Oracle Java SDK 8 
    #
    config.vm.define "client" do |node|
        node.vm.hostname = "client"    
        node.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        node.vm.provision :shell, :inline => "echo '10.11.1.101 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.201 client' >> /etc/hosts"

		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo client completata'"

    end

end
