version: '3'
services:
  subject:
    image: my-registry:5000/word-img-alt
#    ports: 
#    - "8080"
    command: ["-jar", "-Dspring.profiles.active=subject", "word.jar"]
    deploy:
      mode: replicated
      replicas: 1    
  verb:
    image: my-registry:5000/word-img-alt
#    ports: 
#    - "8080"
    command: ["-jar", "-Dspring.profiles.active=verb", "word.jar"]
    deploy:
      mode: replicated
      replicas: 1    
  object:
    image: my-registry:5000/word-img-alt
#    ports: 
#    - "8080"
    command: ["-jar", "-Dspring.profiles.active=object", "word.jar"]
    deploy:
      mode: replicated
      replicas: 1    
  sentence:
    image: my-registry:5000/sentence-img-alt
#    ports: 
#    - "8080"
    deploy:
      mode: replicated
      replicas: 2    
  zuul:
    image: my-registry:5000/sentence-zuul-img-alt
#    container_name: zuul 
    ports:
    - "8080:8080"





