# 
# Vagrantfile per i progetti java-ee, con:
# - un nodo server Java EE 
# - un nodo client 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-16.04"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"

    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/_shared/resources e /home/asw/_shared/scripts) 
    config.vm.synced_folder "../_shared/", "/home/asw/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "glassfish", che prevede: 
    # - Oracle Java SDK 8 
    # - Oracle Java EE 5 (Payara 5.181, basata su GlassFish 5.0) 
    #
    config.vm.define "glassfish" do |node|
        node.vm.hostname = "glassfish"    

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "private_network", ip: "10.11.1.111", virtualbox__intnet: true
        # riusa gli stessi numeri di porta di glassfish, 
        # supponendo che non sia usato localmente 
        node.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
        # node.vm.network "forwarded_port", guest: 8181, host: 8181
        # node.vm.network "forwarded_port", guest: 4848, host: 4848

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
        # node.ssh.forward_x11 = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        # node.vm.provision :shell, :inline => 'apt-get install unzip'
	
		# il server deve avere "10.11.1.111 glassfish" nel file /etc/hosts, 
		# ma non "127.0.1.1 glassfish" ne' "127.0.0.1 glassfish"
		# altrimenti un client remoto non riesce ad accedere al server java ee 
        node.vm.provision :shell, path: "../_shared/scripts/setup-glassfish-server-hosts.sh"

        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        
        node.vm.provision :shell, path: "../_shared/scripts/setup-glassfish-payara5.sh"
        
		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        # avvia glassfish server 
        node.vm.provision "shell", run: "always", path: "../_shared/scripts/start-glassfish.sh"
  
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo glassfish per Java EE completata'"

    end

    #
    # Configurazione del nodo "client", che prevede: 
    # - Oracle Java SDK 8 
    # - appclient per Java EE 8 (da Payara 5.181) 
    # - curl (come client di prova per servizi REST) 
    #
    config.vm.define "client" do |node|
        node.vm.hostname = "client"    
        node.vm.network "private_network", ip: "10.11.1.211", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
        # node.ssh.forward_x11 = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'

        # TEMPORANEO 
        # node.vm.provision :shell, :inline => 'apt-get install unzip'

        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        
        node.vm.provision :shell, path: "../_shared/scripts/setup-glassfish-payara5-appclient.sh"

		# aggiunge "10.11.1.111 glassfish" nel file /etc/hosts, 
        node.vm.provision :shell, path: "../_shared/scripts/setup-glassfish-client-hosts.sh"

        node.vm.provision :shell, inline: "echo  '*** installing curl ***'"
        node.vm.provision :shell, :inline => 'apt-get install libcurl3'
        node.vm.provision :shell, :inline => 'apt-get install curl'
  
		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo client per Java EE completata'"

    end

end
